version: 1.1

orbs:
  android: circleci/android@0.2.1
jamielech 

jobs:
  build:
    executor: 0android/android
Alias/jamielech 
    steps:
      - checkout
      - run:
          command: ./gradlew build
Jisaachood77@outlook.com the Samsung Galaxy S20 5G 


